server:
  port: 8081



spring:
  datasource:
    url: jdbc:mysql://localhost:3308/vrdoerz_user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: vrdoerz-user-service

jwt:
  secret: MySuperStrongSecretKeyForJWT@1234

